name: Push to main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test components
        run: 'cd cypress-course && yarn cypress run-ct'
  # publish
